Create button for playing any tracks
procrastination-team/boombox.frontend pull request #12
Opened 2021-12-11 16:06 UTC by GeekaN2

2021-12-12 12:52 UTC, xalvaine requested changes

2021-12-12 12:52 UTC, xalvaine commented on store/SpotifyStore/index.ts
> +    console.log('tracks', tracks);
Этот лог точно нужен в мастере?

2021-12-12 12:52 UTC, xalvaine commented on store/SpotifyStore/utils.ts
> +}
Я так понимаю, кодстайл предполагает окончание файлов пустой строкой, а тут её нет(

2021-12-12 12:52 UTC, xalvaine commented on usecases/spotifyPlayTrackUsecase.ts
> +}
И тут нет пустой строки в конце

2021-12-20 18:21 UTC, GeekaN2 commented on store/SpotifyStore/utils.ts
> +}
Можно приттиер настроить, правила моего линтера трудновато соблюдать. Думаю, стоит в будущем пару часов уделить код стайлу

2021-12-20 18:23 UTC, grinnds commented
KRASAVA

2021-12-20 18:23 UTC, grinnds approved these changes
WOW SO COOL, WELL DONE

2021-12-20 18:23 UTC, merged